export const surpriseMePromptsEN = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "A mermaid singing with a microphone under the sea, digital art",
  "A futuristic city floating in the clouds, 3D render",
  "A photo of a black cat sitting on a stack of old books, lomography",
  "A painting of a giraffe wearing a top hat and monocle",
  "A digital art illustration of a dragon flying over a medieval castle",
  "A surrealist photo of a man in a suit floating in the sky, holding a briefcase",
  "A watercolor painting of a cat wearing a cowboy hat, riding a unicorn",
  "A photo of a group of penguins wearing sunglasses, sitting on a beach, lomography",
  "A digital art illustration of a robot playing a guitar in a futuristic city",
  "A painting of a giraffe playing basketball",
  "A 3D render of a dragon breathing fire in a medieval battlefield",
  "A photograph of a man in a suit and tie, walking through a field of flowers, lomography",
  "A pencil drawing of a cat playing video games in space",
  "A digital art illustration of a cyborg with a unicorn horn",
  "A watercolor painting of a giraffe playing the violin",
  "A 3D render of a robot playing chess in a futuristic library",
  "A pencil sketch of a cat reading a book in a tree",
  "A digital art illustration of a dragon riding a bicycle",
  "A watercolor painting of a giraffe flying a kite",
  "A photo of a man in a suit and tie, sitting on a bench, feeding the pigeons, lomography",
  "A pencil drawing of a cat flying a plane",
  "A digital art illustration of a robot cooking dinner in a futuristic kitchen",
  "A watercolor painting of a giraffe playing the piano",
  "A 3D render of a dragon playing the drums",
  "A pencil sketch of a cat playing the harmonica in the countryside",
  "A digital art illustration of a cyborg playing chess with a dragon",
  "A watercolor painting of a giraffe playing the accordion",
  "A 3D render of a robot playing the guitar in a futuristic concert",
  "A pencil drawing of a cat playing the saxophone in a jazz club",
  "A digital art illustration of a dragon playing the violin in a medieval castle",
  "A watercolor painting of a giraffe playing the clarinet",
  "A 3D render of a robot playing the trumpet in a futuristic brass band",
  "A pencil sketch of a cat playing the cello in a symphony orchestra",
  "A digital art illustration of a dragon playing the harp in a medieval palace",
  "A watercolor painting of a giraffe playing the flute",
  "A 3D render of a robot playing the trumpet in a futuristic jazz club",
  "A pencil drawing of a cat playing the trumpet in a marching band",
  "A digital art illustration of a dragon playing the drums in a medieval tavern",
  "A watercolor painting of a giraffe playing the trombone",
  "A 3D render of a robot playing the saxophone in a futuristic big band",
  "A pencil sketch of a cat playing the piano in a classical concert",
  "A digital art illustration of a dragon playing the guitar in a medieval jousting tournament",
  "A watercolor painting of a giraffe playing the harp in a forest glade",
  "A 3D render of a robot playing the violin in a futuristic opera",
  "A pencil sketch of a cat playing the trumpet in a circus parade",
  "A digital art illustration of a dragon playing the piano in a medieval castle hall",
  "A watercolor painting of a giraffe playing the cello in a park",
  "A 3D render of a robot playing the harp in a futuristic concert hall",
  "A pencil sketch of a cat playing the flute in a street performance",
  "A digital art illustration of a dragon playing the saxophone in a medieval castle tower",
  "A watercolor painting of a giraffe playing the trombone in a meadow",
  "A 3D render of a robot playing the clarinet in a futuristic concert",
  "A pencil sketch of a cat playing the guitar in a beach concert",
  "A digital art illustration of a dragon playing the cello in a medieval castle dungeon",
  "A watercolor painting of a giraffe playing the piano in a riverbank",
  "A 3D render of a robot playing the flute in a futuristic music festival",
  "A pencil sketch of a cat playing the harp in a forest clearing",
  "A digital art illustration of a dragon playing the trumpet in a medieval castle courtyard",
  "A watercolor painting of a giraffe playing the cello in a mountain meadow",
  "A 3D render of a robot playing the saxophone in a futuristic music concert",
  "A pencil sketch of a cat playing the piano in a park bandstand",
  "A digital art illustration of a dragon playing the guitar in a medieval castle throne room",
  "A watercolor painting of a giraffe playing the trombone in a park gazebo",
  "A 3D render of a robot playing the harp in a futuristic music hall",
  "A pencil sketch of a cat playing the flute in a beach festival",
  "A digital art illustration of a dragon playing the cello in a medieval castle chapel",
  "A watercolor painting of a giraffe playing the trumpet in a park amphitheater",
  "A 3D render of a robot playing the saxophone in a futuristic music festival stage",
  "A pencil sketch of a cat playing the guitar in a forest concert",
  "A digital art illustration of a dragon playing the piano in a medieval castle ballroom",
];

export const surpriseMePromptsVI = [
  "chiếc ghế bành hình quả bơ",
  "một bức tranh sơn dầu giống như giấc mơ siêu thực của Salvador Dalí về một con mèo đang chơi cờ",
  "gấu bông mua hàng tạp hóa ở Nhật Bản, ukiyo-e",
  "một bức tranh sơn dầu của Matisse về một người máy hình người đang chơi cờ",
  "nhà khoa học điên gấu trúc trộn hóa chất lấp lánh, nghệ thuật kỹ thuật số",
  "một bức ảnh macro 35mm chụp hai con chuột ở Hawaii, mỗi con đều mặc bộ đồ bơi nhỏ xíu và mang theo những tấm ván lướt sóng nhỏ xíu, tác phẩm nghệ thuật kỹ thuật số",
  "Kết xuất 3D của một chú cá nhiệt đới dễ thương trong bể cá trên nền xanh đậm, nghệ thuật kỹ thuật số",
  "một phi hành gia đang nằm trong khu nghỉ dưỡng nhiệt đới trong không gian, sóng hơi",
  "một bức tranh sơn dầu vẽ chân dung một con chuột lang nước mặc áo choàng hoàng gia thời trung cổ và đội vương miện trang trí công phu trên nền tối",
  "một cửa sổ kính màu mô tả một chiếc bánh hamburger và khoai tây chiên",
  "một bức vẽ bằng bút chì và màu nước về một thành phố tươi sáng trong tương lai với những chiếc ô tô bay",
  "khu vực tiếp khách trong nhà tràn ngập ánh nắng với một hồ bơi nước trong vắt và một hồ bơi khác với làn nước trong mờ màu hồng pastel, bên cạnh một cửa sổ lớn, nghệ thuật kỹ thuật số",
  "một shiba inu bói toán đọc số phận của bạn trong một chiếc bánh hamburger khổng lồ, nghệ thuật kỹ thuật số",
  '"rái cá biển với bông tai ngọc trai" của Johannes Vermeer',
  "một bức tranh sơn dầu về một con mèo khó chịu trong tàu vũ trụ",
  "bức tranh cáo theo phong cách Đêm đầy sao",
  "một bát súp trông giống như một con quái vật, đan bằng len",
  "Robot đồ chơi sang trọng ngồi dựa vào bức tường màu vàng",
  "Hoàng hôn theo phong cách synthwave trên mặt nước phản chiếu của biển, nghệ thuật kỹ thuật số",
  "Hai tòa tháp tương lai với cây cầu trên cao phủ đầy tán lá tươi tốt, nghệ thuật kỹ thuật số",
  "Kết xuất 3D của khinh khí cầu có màu cầu vồng bay trên mặt hồ phản chiếu",
  "Bìa truyện tranh về một siêu anh hùng đeo tai nghe",
  "Một vụ nổ tập trung của bột đầy màu sắc trên nền đen",
  "Ảnh chó Samoyed thè lưỡi ôm mèo Xiêm trắng",
  "Ảnh chụp một con quái vật lông trắng đứng trong căn phòng màu tím",
  "Một bức ảnh về tác phẩm điêu khắc David đeo tai nghe djing của Michelangelo",
  "Samurai cưỡi ngựa trên sao Hỏa, lomography.",
  "Một chiếc Cadillac hiện đại, kiểu dáng đẹp lái dọc theo đường cao tốc Gardiner với trung tâm thành phố Toronto ở hậu cảnh, với ống kính lóa, chụp ảnh 50 mm",
  "Một bức ảnh thực tế về một phụ nữ trẻ với đôi mắt xanh và mái tóc vàng",
  "Một người đàn ông đứng trước cổng trời đến một chiều không gian khác",
  "Spongebob Squarepants trong Dự án phù thủy Blair",
  "Một con velociraptor đang làm việc ở quầy xúc xích, lomography",
  "Một người đàn ông đi bộ qua những con phố nhộn nhịp của Kowloon vào ban đêm, được thắp sáng bởi nhiều biển hiệu cửa hàng bằng đèn neon sáng, ống kính 50mm",
  "Một bữa BBQ sống động, theo phong cách của một bộ phim hoạt hình Pixar",
  "Câu lạc bộ khiêu vũ người máy tương lai, đèn neon",
  "Anime Nhật Bản Star Wars 1990 đã thất lạc từ lâu",
  "Một chiếc bánh hamburger có hình khối Rubik, chụp ảnh đồ ăn chuyên nghiệp",
  "Nhím Synthwave, Cyberpunk Blade Runner",
  "Một phi hành gia bắt gặp một dạng sống ngoài hành tinh trên một hành tinh xa xôi, nhiếp ảnh",
  "Khủng long khám phá Cape Town, nhiếp ảnh",
  "Một người đàn ông yêu máy tính của mình, nghệ thuật kỹ thuật số",
  "Ảnh chụp một người máy khám phá Tokyo về đêm, lomography",
  "Dracula đi bộ trên đường phố New York vào những năm 1920, ảnh đen trắng",
  "Máy bay sóng tổng hợp",
  "Một người đàn ông lang thang qua những con đường mưa ở Tokyo, với những biển hiệu đèn neon sáng, 50mm",
  "Tàu con thoi bay trên Cape Town, nghệ thuật kỹ thuật số",
  "Nàng tiên cá hát bằng micrô dưới biển, nghệ thuật kỹ thuật số",
  "Thành phố tương lai lơ lửng trên mây, kết xuất 3D",
  "Ảnh con mèo đen ngồi trên chồng sách cũ, lomography",
  "Bức tranh hươu cao cổ đội mũ chóp và đeo kính một mắt",
  "Một minh họa nghệ thuật kỹ thuật số về một con rồng bay trên lâu đài thời trung cổ",
  "Một bức ảnh siêu thực về một người đàn ông mặc vest lơ lửng trên bầu trời, tay cầm một chiếc cặp",
  "Tranh màu nước mèo đội mũ cao bồi cưỡi kỳ lân",
  "Ảnh chụp một nhóm chim cánh cụt đeo kính râm, ngồi trên bãi biển, lomography",
  "Một minh họa nghệ thuật kỹ thuật số về một rô-bốt chơi ghi-ta trong một thành phố tương lai",
  "Tranh hươu cao cổ chơi bóng rổ",
  "Kết xuất 3D của một con rồng phun lửa trong chiến trường thời trung cổ",
  "Bức ảnh chụp một người đàn ông mặc vest và thắt cà vạt, đi qua cánh đồng hoa, lomography",
  "Một bức tranh vẽ con mèo chơi trò chơi điện tử trong không gian bằng bút chì",
  "Một minh họa nghệ thuật kỹ thuật số về người máy với chiếc sừng kỳ lân",
  "Bức tranh màu nước vẽ con hươu cao cổ chơi vĩ cầm",
  "Kết xuất 3D của rô-bốt chơi cờ trong thư viện tương lai",
  "Bản phác thảo bằng bút chì về một con mèo đang đọc sách trên cây",
  "Một minh họa nghệ thuật kỹ thuật số về một con rồng cưỡi xe đạp",
  "Tranh màu nước hươu cao cổ thả diều",
  "Bức ảnh một người đàn ông mặc vest và thắt cà vạt, ngồi trên băng ghế, cho chim bồ câu ăn, lomography",
  "Một bức tranh vẽ con mèo đang lái máy bay bằng bút chì",
  "Một minh họa nghệ thuật kỹ thuật số về một người máy đang nấu bữa tối trong một căn bếp của tương lai",
  "Bức tranh màu nước vẽ con hươu cao cổ đang chơi piano",
  "Kết xuất 3D của trò chơi rồng chơi trống",
  "Một bức phác thảo bằng bút chì về một con mèo đang chơi kèn harmonica ở vùng nông thôn",
  "Một minh họa nghệ thuật kỹ thuật số về một người máy chơi cờ với một con rồng",
  "Bức tranh màu nước vẽ con hươu cao cổ chơi đàn accordion",
  "Kết xuất 3D của một rô-bốt chơi ghi-ta trong một buổi hòa nhạc của tương lai",
  "Một bức vẽ bút chì về một con mèo chơi saxophone trong câu lạc bộ nhạc jazz",
  "Một minh họa nghệ thuật kỹ thuật số về một con rồng chơi vĩ cầm trong một lâu đài thời trung cổ",
  "Bức tranh màu nước vẽ con hươu cao cổ chơi kèn clarinet",
  "Hình ảnh 3D của một rô-bốt chơi kèn trong ban nhạc kèn đồng của tương lai",
  "Một bản phác thảo bằng bút chì về một con mèo chơi đàn Cello trong một dàn nhạc giao hưởng",
  "Một minh họa nghệ thuật kỹ thuật số về một con rồng chơi đàn hạc trong một cung điện thời trung cổ",
  "Tranh màu nước hươu cao cổ thổi sáo",
  "Hình ảnh 3D của một rô-bốt chơi kèn trong câu lạc bộ nhạc jazz của tương lai",
  "Một bức vẽ bằng bút chì về một con mèo đang chơi kèn trong một ban nhạc diễu hành",
  "Một minh họa nghệ thuật kỹ thuật số về một con rồng đang chơi trống trong một quán rượu thời trung cổ",
  "Bức tranh màu nước vẽ con hươu cao cổ chơi kèn trombone",
  "Kết xuất 3D của một rô-bốt chơi saxophone trong một ban nhạc lớn của tương lai",
  "Một bản phác thảo bút chì về một con mèo chơi piano trong một buổi hòa nhạc cổ điển",
  "Một minh họa nghệ thuật kỹ thuật số về một con rồng chơi ghi-ta trong một giải đấu thương thời trung cổ",
  "Bức tranh màu nước vẽ con hươu cao cổ chơi đàn hạc trong rừng trảng",
  "Kết xuất 3D của một rô-bốt chơi vĩ cầm trong một vở opera của tương lai",
  "Một bản phác thảo bằng bút chì về một con mèo đang thổi kèn trong đoàn xiếc diễu hành",
  "Một minh họa nghệ thuật kỹ thuật số về một con rồng chơi piano trong sảnh lâu đài thời trung cổ",
  "Bức tranh màu nước vẽ con hươu cao cổ chơi đàn Cello trong công viên",
  "Kết xuất 3D của một rô-bốt chơi đàn hạc trong phòng hòa nhạc tương lai",
  "Một bản phác thảo bằng bút chì về một con mèo đang thổi sáo trong một buổi biểu diễn đường phố",
  "Một minh họa nghệ thuật kỹ thuật số về một con rồng chơi saxophone trong tòa tháp lâu đài thời trung cổ",
  "Bức tranh màu nước vẽ con hươu cao cổ chơi kèn trombone trên đồng cỏ",
  "Kết xuất 3D của một rô-bốt chơi kèn clarinet trong một buổi hòa nhạc tương lai",
  "Bản phác thảo bút chì về một con mèo chơi ghi-ta trong một buổi hòa nhạc trên bãi biển",
  "Một minh họa nghệ thuật kỹ thuật số về một con rồng chơi đàn cello trong ngục tối lâu đài thời trung cổ",
  "Bức tranh màu nước vẽ con hươu cao cổ chơi đàn bên bờ sông",
  "Hình ảnh 3D của một rô-bốt thổi sáo trong một lễ hội âm nhạc tương lai",
  "Một bản phác thảo bằng bút chì về một con mèo đang chơi đàn hạc trong một khu rừng thưa",
  "Một minh họa nghệ thuật kỹ thuật số về một con rồng đang thổi kèn trong sân lâu đài thời trung cổ",
  "Bức tranh màu nước vẽ con hươu cao cổ chơi đàn Cello trên đồng cỏ trên núi",
  "Kết xuất 3D của rô-bốt chơi saxophone trong một buổi hòa nhạc tương lai",
  "Một bản phác thảo bằng bút chì về một con mèo đang chơi đàn piano trong một ban nhạc ở công viên",
  "Một minh họa nghệ thuật kỹ thuật số về một con rồng chơi ghi-ta trong phòng ngai vàng của lâu đài thời trung cổ",
  "Bức tranh màu nước vẽ một con hươu cao cổ chơi kèn trombone trong vọng lâu của công viên",
  "Hình ảnh 3D của một rô-bốt chơi đàn hạc trong hội trường âm nhạc tương lai",
  "Một bức phác thảo bằng bút chì về một con mèo đang thổi sáo trong lễ hội bãi biển",
  "Một minh họa nghệ thuật kỹ thuật số về một con rồng chơi đàn cello trong nhà nguyện lâu đài thời trung cổ",
  "Bức tranh màu nước về một con hươu cao cổ đang thổi kèn trong nhà hát ngoài trời ở công viên",
  "Hình ảnh 3D của một rô-bốt chơi saxophone trên sân khấu lễ hội âm nhạc tương lai",
  "Bản phác thảo bút chì về một con mèo chơi ghi-ta trong một buổi hòa nhạc trong rừng",
  "Một minh họa nghệ thuật kỹ thuật số về một con rồng chơi piano trong phòng khiêu vũ của lâu đài thời trung cổ",
];

export const surpriseMePromptsDE = [
  "Sessel in Form einer Avocado",
  "ein surrealistisches, traumhaftes Ölgemälde von Salvador Dalí einer Katze, die Dame spielt",
  "Teddybären beim Lebensmitteleinkauf in Japan, Ukiyo-e",
  "ein Ölgemälde von Matisse eines humanoiden Roboters, der Schach spielt",
  "verrückter Panda-Wissenschaftler mischt funkelnde Chemikalien, digitale Kunst",
  "Ein 35-mm-Makrofoto von zwei Mäusen auf Hawaii, sie tragen jeweils winzige Badeanzüge und tragen winzige Surfbretter, digitale Kunst",
  "3D-Darstellung eines niedlichen tropischen Fisches in einem Aquarium auf dunkelblauem Hintergrund, digitale Kunst",
  "ein Astronaut, der in einem tropischen Resort im Weltraum faulenzt, Vaporwave",
  "ein Ölgemäldeporträt eines Capybara in mittelalterlichen königlichen Gewändern und einer verzierten Krone auf dunklem Hintergrund",
  "ein Buntglasfenster, das einen Hamburger und Pommes Frites darstellt",
  "eine Bleistift- und Aquarellzeichnung einer leuchtenden Stadt in der Zukunft mit fliegenden Autos",
  "ein sonnendurchfluteter Indoor-Loungebereich mit einem Pool mit klarem Wasser und einem weiteren Pool mit durchscheinendem pastellrosa Wasser, neben einem großen Fenster, digitale Kunst",
  "ein wahrsagender shiba inu, der dein schicksal in einem riesigen hamburger liest, digitale kunst",
  '"Seeotter mit Perlenohrring" von Johannes Vermeer',
  "eine Ölpastellzeichnung einer genervten Katze in einem Raumschiff",
  "ein Gemälde eines Fuchses im Stil der Sternennacht",
  "eine Schüssel Suppe, die aussieht wie ein Monster, aus Wolle gestrickt",
  "Ein Plüschroboter, der an einer gelben Wand sitzt",
  "Ein Sonnenuntergang im Synthwave-Stil über dem reflektierenden Wasser des Meeres, digitale Kunst",
  "Zwei futuristische Türme mit einer mit üppigem Laub bedeckten Skybridge, digitale Kunst",
  "Eine 3D-Darstellung eines regenbogenfarbenen Heißluftballons, der über einem reflektierenden See fliegt",
  "Ein Comic-Cover eines Superhelden mit Kopfhörern",
  "Eine zentrierte Explosion aus buntem Pulver auf schwarzem Hintergrund",
  "Ein Foto eines Samojeden mit herausgestreckter Zunge, der eine weiße Siamkatze umarmt",
  "Ein Foto eines Monsters aus weißem Fell, das in einem violetten Raum steht",
  "Ein Foto von Michelangelos David-Skulptur mit Kopfhörern beim Auflegen",
  "Ein Samurai auf einem Pferd auf dem Mars, Lomographie.",
  "Ein realistisches Foto einer jungen Frau mit blauen Augen und blonden Haaren",
  "Ein Mann steht vor einem Sternentor in eine andere Dimension",
  "SpongeBob Schwammkopf im Blair Witch Project",
  "Ein Velociraptor, der an einem Hotdog-Stand arbeitet, Lomographie",
  "Ein Mann, der nachts durch die belebten Straßen von Kowloon geht, beleuchtet von vielen hellen Neon-Ladenschildern, 50-mm-Objektiv",
  "Ein lebendiges BBQ im Stil eines Pixar-Animationsfilms",
  "Ein futuristischer Cyborg-Tanzclub, Neonlichter",
  "Der lange verschollene japanische Star Wars 1990 Anime",
  "Ein Hamburger in Form eines Zauberwürfels, professionelle Food-Fotografie",
  "Ein Synthwave-Igel, Blade Runner Cyberpunk",
  "Ein Astronaut trifft auf einem fernen Planeten auf eine außerirdische Lebensform, Fotografie",
  "Ein Dinosaurier, der Kapstadt erkundet, Fotografie",
  "Ein Mann, der sich in seinen Computer verliebt, digitale Kunst",
  "Ein Foto eines Cyborgs, der Tokio bei Nacht erkundet, Lomographie",
  "Dracula geht in den 1920er Jahren durch die Straßen von New York City, Schwarz-Weiß-Fotografie",
  "Synthwave-Flugzeug",
  "Ein Space Shuttle fliegt über Kapstadt, digitale Kunst",
  "Eine Meerjungfrau, die mit einem Mikrofon unter dem Meer singt, digitale Kunst",
  "Eine futuristische Stadt, die in den Wolken schwebt, 3D-Darstellung",
  "Ein Foto einer schwarzen Katze, die auf einem Stapel alter Bücher sitzt, Lomografie",
  "Gemälde einer Giraffe mit Zylinder und Monokel",
  "Eine digitale Kunstillustration eines Drachens, der über eine mittelalterliche Burg fliegt",
  "Ein surrealistisches Foto eines Mannes im Anzug, der am Himmel schwebt und eine Aktentasche hält",
  "Ein Aquarellbild einer Katze mit Cowboyhut, die auf einem Einhorn reitet",
  "Ein Foto einer Gruppe von Pinguinen mit Sonnenbrille, die an einem Strand sitzen, Lomographie",
  "Eine digitale Kunstillustration eines Roboters, der in einer futuristischen Stadt Gitarre spielt",
  "Gemälde einer Basketball spielenden Giraffe",
  "Eine 3D-Darstellung eines feuerspeienden Drachen auf einem mittelalterlichen Schlachtfeld",
  "Ein Foto von einem Mann in Anzug und Krawatte, der durch ein Blumenfeld geht, Lomografie",
  "Eine Bleistiftzeichnung einer Katze, die Videospiele im Weltraum spielt",
  "Eine digitale Kunstillustration eines Cyborgs mit einem Einhornhorn",
  "Aquarellbild einer Giraffe, die Geige spielt",
  "Eine 3D-Darstellung eines Schach spielenden Roboters in einer futuristischen Bibliothek",
  "Eine Bleistiftskizze einer Katze, die ein Buch in einem Baum liest",
  "Eine digitale Kunstillustration eines Drachen, der Fahrrad fährt",
  "Ein Aquarellbild einer Giraffe, die einen Drachen fliegt",
  "Ein Foto von einem Mann in Anzug und Krawatte, der auf einer Bank sitzt und die Tauben füttert, Lomographie",
  "Eine Bleistiftzeichnung einer Katze, die ein Flugzeug fliegt",
  "Eine digitale Kunstillustration eines Roboters, der in einer futuristischen Küche Abendessen kocht",
  "Aquarellbild einer klavierspielenden Giraffe",

  "Eine 3D-Darstellung eines Drachen, der Schlagzeug spielt",
  "Eine Bleistiftskizze einer Katze, die auf dem Land Mundharmonika spielt",
  "Eine digitale Kunstillustration eines Cyborgs, der mit einem Drachen Schach spielt",
  "Ein Aquarell einer Giraffe, die das Akkordeon spielt",
  "Eine 3D-Darstellung eines Roboters, der in einem futuristischen Konzert Gitarre spielt",
  "Eine Bleistiftzeichnung einer Katze, die in einem Jazzclub Saxophon spielt",
  "Eine digitale Kunstillustration eines Drachen, der in einer mittelalterlichen Burg Geige spielt",
  "Aquarellbild einer klarinettenspielenden Giraffe",
  "Eine 3D-Darstellung eines Trompeten spielenden Roboters in einer futuristischen Blaskapelle",
  "Eine Bleistiftskizze einer Katze, die in einem Sinfonieorchester Cello spielt",
  "Eine digitale Kunstillustration eines Drachen, der in einem mittelalterlichen Palast Harfe spielt",
  "Aquarellbild einer Flöte spielenden Giraffe",
  "Eine 3D-Darstellung eines Roboters, der in einem futuristischen Jazzclub Trompete spielt",
  "Bleistiftzeichnung einer Katze, die in einer Blaskapelle Trompete spielt",
  "Eine digitale Kunstillustration eines Drachen, der in einer mittelalterlichen Taverne Schlagzeug spielt",
  "Aquarellbild einer posaunenspielenden Giraffe",
  "Eine 3D-Darstellung eines Saxophon spielenden Roboters in einer futuristischen Big Band",
  "Eine Bleistiftskizze einer Katze, die in einem klassischen Konzert Klavier spielt",
  "Eine digitale Kunstillustration eines Drachen, der in einem mittelalterlichen Ritterturnier Gitarre spielt",
  "Aquarellbild einer harfenspielenden Giraffe auf einer Waldlichtung",
  "Eine 3D-Darstellung eines Roboters, der in einer futuristischen Oper Geige spielt",
  "Eine Bleistiftskizze einer Katze, die bei einer Zirkusparade Trompete spielt",
  "Eine digitale Kunstillustration eines Drachen, der in einer mittelalterlichen Burghalle Klavier spielt",
  "Ein Aquarell einer Giraffe, die in einem Park Cello spielt",
  "Eine 3D-Darstellung eines Harfen spielenden Roboters in einem futuristischen Konzertsaal",
  "Eine Bleistiftskizze einer Katze, die bei einer Straßenaufführung Flöte spielt",
  "Eine digitale Kunstillustration eines Drachen, der in einem mittelalterlichen Burgturm Saxophon spielt",
  "Aquarellbild einer posaunenspielenden Giraffe auf einer Wiese",
  "Eine 3D-Darstellung eines Roboters, der in einem futuristischen Konzert Klarinette spielt",
  "Eine Bleistiftskizze einer Katze, die bei einem Strandkonzert Gitarre spielt",
  "Eine digitale Kunstillustration eines Drachen, der in einem mittelalterlichen Burgverlies Cello spielt",
  "Aquarellbild einer klavierspielenden Giraffe an einem Flussufer",
  "Eine 3D-Darstellung eines Roboters, der auf einem futuristischen Musikfestival Flöte spielt",
  "Bleistiftskizze einer Harfe spielenden Katze auf einer Waldlichtung",
  "Eine digitale Kunstillustration eines Drachen, der in einem mittelalterlichen Burghof Trompete spielt",
  "Aquarell einer Giraffe, die auf einer Bergwiese Cello spielt",
  "Eine 3D-Darstellung eines Saxophon spielenden Roboters in einem futuristischen Musikkonzert",
  "Eine Bleistiftskizze einer Katze, die in einem Parkpavillon Klavier spielt",
  "Eine digitale Kunstillustration eines Drachen, der in einem mittelalterlichen Burgthronsaal Gitarre spielt",
  "Ein Aquarell einer Giraffe, die Posaune in einer Parklaube spielt",
  "Eine 3D-Darstellung eines Harfen spielenden Roboters in einem futuristischen Musiksaal",
  "Eine Bleistiftskizze einer Katze, die bei einem Strandfest Flöte spielt",
  "Eine digitale Kunstillustration eines Drachen, der in einer mittelalterlichen Burgkapelle Cello spielt",
  "Ein Aquarell einer trompetenspielenden Giraffe in einem Amphitheater im Park",
  "Eine 3D-Darstellung eines Saxophon spielenden Roboters auf einer futuristischen Musikfestival-Bühne",
  "Eine Bleistiftskizze einer Katze, die in einem Waldkonzert Gitarre spielt",
  "Eine digitale Kunstillustration eines Drachen, der in einem Ballsaal einer mittelalterlichen Burg Klavier spielt",
];
