export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "A mermaid singing with a microphone under the sea, digital art",
  "A futuristic city floating in the clouds, 3D render",
  "A photo of a black cat sitting on a stack of old books, lomography",
  "A painting of a giraffe wearing a top hat and monocle",
  "A digital art illustration of a dragon flying over a medieval castle",
  "A surrealist photo of a man in a suit floating in the sky, holding a briefcase",
  "A watercolor painting of a cat wearing a cowboy hat, riding a unicorn",
  "A photo of a group of penguins wearing sunglasses, sitting on a beach, lomography",
  "A digital art illustration of a robot playing a guitar in a futuristic city",
  "A painting of a giraffe playing basketball",
  "A 3D render of a dragon breathing fire in a medieval battlefield",
  "A photograph of a man in a suit and tie, walking through a field of flowers, lomography",
  "A pencil drawing of a cat playing video games in space",
  "A digital art illustration of a cyborg with a unicorn horn",
  "A watercolor painting of a giraffe playing the violin",
  "A 3D render of a robot playing chess in a futuristic library",
  "A pencil sketch of a cat reading a book in a tree",
  "A digital art illustration of a dragon riding a bicycle",
  "A watercolor painting of a giraffe flying a kite",
  "A photo of a man in a suit and tie, sitting on a bench, feeding the pigeons, lomography",
  "A pencil drawing of a cat flying a plane",
  "A digital art illustration of a robot cooking dinner in a futuristic kitchen",
  "A watercolor painting of a giraffe playing the piano",
  "A 3D render of a dragon playing the drums",
  "A pencil sketch of a cat playing the harmonica in the countryside",
  "A digital art illustration of a cyborg playing chess with a dragon",
  "A watercolor painting of a giraffe playing the accordion",
  "A 3D render of a robot playing the guitar in a futuristic concert",
  "A pencil drawing of a cat playing the saxophone in a jazz club",
  "A digital art illustration of a dragon playing the violin in a medieval castle",
  "A watercolor painting of a giraffe playing the clarinet",
  "A 3D render of a robot playing the trumpet in a futuristic brass band",
  "A pencil sketch of a cat playing the cello in a symphony orchestra",
  "A digital art illustration of a dragon playing the harp in a medieval palace",
  "A watercolor painting of a giraffe playing the flute",
  "A 3D render of a robot playing the trumpet in a futuristic jazz club",
  "A pencil drawing of a cat playing the trumpet in a marching band",
  "A digital art illustration of a dragon playing the drums in a medieval tavern",
  "A watercolor painting of a giraffe playing the trombone",
  "A 3D render of a robot playing the saxophone in a futuristic big band",
  "A pencil sketch of a cat playing the piano in a classical concert",
  "A digital art illustration of a dragon playing the guitar in a medieval jousting tournament",
  "A watercolor painting of a giraffe playing the harp in a forest glade",
  "A 3D render of a robot playing the violin in a futuristic opera",
  "A pencil sketch of a cat playing the trumpet in a circus parade",
  "A digital art illustration of a dragon playing the piano in a medieval castle hall",
  "A watercolor painting of a giraffe playing the cello in a park",
  "A 3D render of a robot playing the harp in a futuristic concert hall",
  "A pencil sketch of a cat playing the flute in a street performance",
  "A digital art illustration of a dragon playing the saxophone in a medieval castle tower",
  "A watercolor painting of a giraffe playing the trombone in a meadow",
  "A 3D render of a robot playing the clarinet in a futuristic concert",
  "A pencil sketch of a cat playing the guitar in a beach concert",
  "A digital art illustration of a dragon playing the cello in a medieval castle dungeon",
  "A watercolor painting of a giraffe playing the piano in a riverbank",
  "A 3D render of a robot playing the flute in a futuristic music festival",
  "A pencil sketch of a cat playing the harp in a forest clearing",
  "A digital art illustration of a dragon playing the trumpet in a medieval castle courtyard",
  "A watercolor painting of a giraffe playing the cello in a mountain meadow",
  "A 3D render of a robot playing the saxophone in a futuristic music concert",
  "A pencil sketch of a cat playing the piano in a park bandstand",
  "A digital art illustration of a dragon playing the guitar in a medieval castle throne room",
  "A watercolor painting of a giraffe playing the trombone in a park gazebo",
  "A 3D render of a robot playing the harp in a futuristic music hall",
  "A pencil sketch of a cat playing the flute in a beach festival",
  "A digital art illustration of a dragon playing the cello in a medieval castle chapel",
  "A watercolor painting of a giraffe playing the trumpet in a park amphitheater",
  "A 3D render of a robot playing the saxophone in a futuristic music festival stage",
  "A pencil sketch of a cat playing the guitar in a forest concert",
  "A digital art illustration of a dragon playing the piano in a medieval castle ballroom",
];
